# Document 1
debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*" # ????? ????? ? ??????? ?????? ?.

logging:
  level:
    org.example.boardservice: debug # root ????? ???? ?? ???? ??? ??? ??? ??.
    org.springframework.web.servlet: debug # servlet ????? ???? ?? ??? ??? ??? ??? ??
    org.hibernate.type.descriptor.sql.BasicBinder: trace # JPA ??? Query ??? ??? ??? ?? ??

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: uno
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # boot ver2.4?? ??, ???? ??????? ?? ? ???.
    hibernate:
      ddl-auto: create # entity? ?? ??? ???? ???? ???? ddl ?? ??
    show-sql: true # sql ?? ????
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100 # ?? ??? ?? ?
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated